name: Packages Split

on:
    push:
        branches:
            - master
        tags:
            - '*'
    workflow_dispatch: ~

env:
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    REPOSITORY_ORGANIZATION: 'ferror'

jobs:
    packages_split:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                # define package to repository map
                package:
                    -   local_path: 'logging-bundle'
                        split_repository: 'logging-bundle'

                    -   local_path: 'messaging-bundle'
                        split_repository: 'messaging-bundle'

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v3

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                name: Split Package Without Tag
                uses: symplify/monorepo-split-github-action@2.2
                with:
                    # ↓ split "packages/easy-coding-standard" directory
                    package_directory: 'packages/${{ matrix.package.local_path }}'

                    # ↓ into https://github.com/symplify/easy-coding-standard repository
                    repository_organization: ${{ env.REPOSITORY_ORGANIZATION }}
                    repository_name: ${{ matrix.package.split_repository }}

                    # ↓ the user signed under the split commit
                    user_name: "GitHub Action"
                    user_email: "action@github.com"

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                name: Split Package With Tag
                uses: symplify/monorepo-split-github-action@2.2
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    # ↓ split "packages/easy-coding-standard" directory
                    package_directory: 'packages/${{ matrix.package.local_path }}'

                    # ↓ into https://github.com/symplify/easy-coding-standard repository
                    repository_organization: ${{ env.REPOSITORY_ORGANIZATION }}
                    repository_name: ${{ matrix.package.split_repository }}

                    # ↓ the user signed under the split commit
                    user_name: "GitHub Action"
                    user_email: "action@github.com"
